### ISSUE TITLE
Doesn't 'persist' with Jenkins 2.0 Pipeline

### ISSUE THREAD

**Issue by james-masson** [jenkinsci/persistent-parameter-plugin#1]
Doesn't work in combination with Jenkins 2.0 Pipelines.

It functions as a parameter just fine, but the successful parameters are not remembered for the next job run.

**Comment by ashu16815** [comment]
https://github.com/ashu16815/persistent-parameter-plugin 
You may use this

**Comment by ashu16815** [comment]
Hi,

This issue is resolved.

Cheers,
Ankit

**Comment by dpreilan** [comment]
fyi, I was continuing to have issues even with Ankit's changes.
It turned out to be security related. I had to give anonymous user permission to read jobs. This allowed the plugin which runs as anonymous the ability the get data from Hudson.getInstance().getAllItems()

**Comment by wangyoucao577** [comment]
Meet same issue with Jenkins Pipeline 2.5.

**Comment by mbasri** [comment]
+1

**Comment by jhrabi** [comment]
+1

**Comment by DaleBetts** [comment]
+1

**Comment by anupshrestha** [comment]
+1

**Comment by jkroepke** [comment]
I found a good workaround with [Extended Choice Parameter](https://plugins.jenkins.io/extended-choice-parameter).

On project configuration, use `Extended Choice Parameter`

Parameter Type: Text Box

Script type: `Groovy Script`

Groovy script (same for value and default value):
```groovy
try {
  return jenkins.getItemByFullName(jobName).getLastBuild().getProperties()["environment"][parameterName]
} catch (all) {
  return defaultValue
}
```
Properties:
```groovy
jobName=Folder/Deploy
parameterName=VERSION
defaultValue=1.0
```

**Comment by pedrodelgado81** [comment]
Same problem :(

**Comment by amritihealthlabs** [comment]
issue still persists, the latest value of build not retained.

**Comment by donhui** [comment]
+1

**Comment by 1508zb** [comment]
> I found a good workaround with [Extended Choice Parameter](https://plugins.jenkins.io/extended-choice-parameter).
> 
> On project configuration, use `Extended Choice Parameter`
> 
> Parameter Type: Text Box
> 
> Script type: `Groovy Script`
> 
> Groovy script (same for value and default value):
> 
> ```groovy
> try {
>   return jenkins.getItemByFullName(jobName).getLastBuild().getProperties()["environment"][parameterName]
> } catch (all) {
>   return defaultValue
> }
> ```
> 
> Properties:
> 
> ```groovy
> jobName=Folder/Deploy
> parameterName=VERSION
> defaultValue=1.0
> ```



> I found a good workaround with [Extended Choice Parameter](https://plugins.jenkins.io/extended-choice-parameter).
> 
> On project configuration, use `Extended Choice Parameter`
> 
> Parameter Type: Text Box
> 
> Script type: `Groovy Script`
> 
> Groovy script (same for value and default value):
> 
> ```groovy
> try {
>   return jenkins.getItemByFullName(jobName).getLastBuild().getProperties()["environment"][parameterName]
> } catch (all) {
>   return defaultValue
> }
> ```
> 
> Properties:
> 
> ```groovy
> jobName=Folder/Deploy
> parameterName=VERSION
> defaultValue=1.0
> ```

Hi! Can you describe your practice in more detail? Maybe you can give an example,thank you so much!
