### ISSUE TITLE
release 1.3 not yet listed in  https://plugins.jenkins.io/persistent-parameter/#releases

### ISSUE THREAD

**Issue by arungitan** [jenkinsci/persistent-parameter-plugin#13]
I requested our CI ops to upgrade our plugin but they said Jenkins doesn't give the option to upgrade from 1.2 to this version, probably since the above url is not yet updated.  Any idea when the plugins.jenkins.io will be updated?

**Comment by ro-kr** [comment]
@greg2001 has built the release, maybe he knows more?

**Comment by greg2001** [comment]
Should be there now, sorry for the inconvenience.

**Comment by arungitan** [comment]
Thanks!
