### ISSUE TITLE
Highlighting text with HTML

### ISSUE THREAD

**Issue by aperesypkin** [jenkinsci/persistent-parameter-plugin#4]
Hello!

Doesn't work HTML highlighting for description's text in build's parameters, but highlighting works for default Jenkins build's parameters.

Jenkins version 2.90
Persistent Parameter Plugin version 1.1

![2017-11-17_1445](https://user-images.githubusercontent.com/10241455/32945843-094a8e90-cba6-11e7-8b62-f219240ad24b.png)

![2017-11-17_1445_001](https://user-images.githubusercontent.com/10241455/32945850-0e97d6e6-cba6-11e7-8e65-e41a6579ab37.png)

**Comment by ro-kr** [comment]
This issue has been fixed by #12 and is part of plugin release 1.3.
